services:
  httpgw:
    build:
      context: .
      dockerfile: cmd/eir-gateway/Dockerfile
    image: eir-http-gateway
    container_name: eir-httpgw
    ports:
      - "36110:36110"   # HTTP gateway port
      - "2345:2345"
      - "9090:9090"   # API/Stats port (if configured)
    # volumes:
    #   - ./misc/haproxy-init.cfg:/etc/haproxy/haproxy.cfg:ro
    #   - ./misc/gateway-entrypoint.sh:/entrypoint.sh
    environment:
      - LOG_LEVEL=debug
      - TARGET_GOV=192.168.13.67:36100
      - SERVICE_IP=192.168.13.67
      # - HAPROXY_RUNTIME_SOCKET=/tmp/http-gw/runtime.sock
      # - HAPROXY_PID_FILE=/tmp/http-gw/haproxy.pidfile
      # - HAPROXY_CONFIG=/etc/haproxy/haproxy.cfg
      # - HAPROXY_BIN=/usr/local/sbin/haproxy
    restart: unless-stopped
    networks:
      - httpgw-net

volumes:
  haproxy-runtime:

networks:
  httpgw-net:
    driver: bridge

# echo 'show servers state eir_be' | socat stdio /tmp/haproxy-gateway/haproxy-runtime-api.sock
# echo 'show backend' | socat stdio /tmp/haproxy-gateway/haproxy-runtime-api.sock
# echo 'show stat' | socat stdio /tmp/haproxy-gateway/haproxy-runtime-api.sock | awk -F',' '{print $1, $2, $18}' | grep -E "udr"